# Generated by Django 4.2.6 on 2023-12-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/products/funsush.jpg', upload_to='uploads/category/'),
        ),
    ]
