# Generated by Django 4.2.6 on 2024-01-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_buyer_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
