# Generated by Django 4.2.6 on 2024-01-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_delivery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_status',
            new_name='order_status',
        ),
    ]
