# Generated by Django 4.2.6 on 2024-01-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_is_sale_remove_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Delivery', 'On Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
