# Generated by Django 4.2.6 on 2024-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Pay On Delivery', 'Pay on delivery'), ('Khalti Payment', 'Khalti Payment')], default='Pay On Delivery', max_length=20),
        ),
    ]
